DirectoryPath: dist

CheckInternalHash: false
CheckMailto: false
CheckTel: false
IgnoreURLs:
  - twitter.com
  - facebook.com
  - reddit.com
  - groups.google.com
  - console.cloud.google.com
  - linkedin.com
  - angel.co
  - player.vimeo.com
  - crunchbase.com
  - en.wikipedia.org
  - localhost
  - bilibili.com
IgnoreDirs:
  - docs/v1.0
  - docs/v2.0
  - docs/v2.1-legacy
  - docs-cn/v1.0
  - docs-cn/v2.0
  - docs-cn/v2.1-legacy
IgnoreInternalEmptyHash: true
IgnoreEmptyHref: true
IgnoreDirectoryMissingTrailingSlash: true
IgnoreAltMissing: true
ExternalTimeout: 10
OutputDir: .htmltest
